package main

import (
	"fmt"
	"time"
)

// generateAlertEmailBody creates an HTML email body for the weekly alert report
func generateAlertEmailBody(complianceStandard, cloudType string, alertCount int) string {
	timestamp := time.Now().Format("2006-01-02 15:04:05")

	// Determine colors based on cloud type
	var bgColor, textColor string
	if cloudType == "AWS" {
		bgColor = "#e8f5e9"
		textColor = "#2e7d32"
	} else {
		bgColor = "#e3f2fd"
		textColor = "#1565c0"
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly CSPM Alert Report - %s</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px;">
        <h1 style="color: #2c3e50; margin-top: 0;">Weekly CSPM Alert Report - %s</h1>

        <p style="color: #666;">Dear Team,</p>

        <p>Please find below the summary of %s CSPM alerts generated in the past 7 days.</p>

        <div style="background-color: #fff; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h2 style="margin-top: 0; color: #34495e;">Report Details</h2>
            <table style="width: 100%%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Cloud Provider:</strong></td>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;">%s</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Compliance Standard:</strong></td>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;">%s</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Report Generated:</strong></td>
                    <td style="padding: 8px 0; border-bottom: 1px solid #eee;">%s</td>
                </tr>
            </table>
        </div>

        <div style="background-color: #fff; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h2 style="margin-top: 0; color: #34495e;">Alert Summary</h2>
            <table style="width: 100%%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 10px; background-color: %s; border-radius: 4px;">
                        <strong>Total Alerts:</strong>
                    </td>
                    <td style="padding: 10px; background-color: %s; border-radius: 4px; text-align: center;">
                        <span style="font-size: 24px; font-weight: bold; color: %s;">%d</span>
                    </td>
                </tr>
            </table>
        </div>

        <p>Please review the attached CSV file for detailed information about each alert, including remediation recommendations.</p>

        <div style="background-color: #fff3e0; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <strong>Next Steps:</strong>
            <ul style="margin: 10px 0 0 0;">
                <li>Review alerts and prioritize based on severity</li>
                <li>Implement remediation steps provided in the Recommendation column</li>
                <li>Assign to respective cloud teams for follow-up</li>
            </ul>
        </div>

        <p style="color: #999; font-size: 12px; margin-top: 30px;">
            This is an automated report generated by the Adam system. Please do not reply to this email.
        </p>
    </div>
</body>
</html>`, cloudType, cloudType, cloudType, cloudType, complianceStandard, timestamp, bgColor, bgColor, textColor, alertCount)

	return html
}
